driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
connectionString=jdbc:sqlserver://LAPTOP-60PARR74:1433;databaseName=Spotitube;user=junjie;password=junjiejuan;encrypt=false;trustServerCertifcate=true
